language: python
sudo: required
dist: trusty
python:
- '3.5'
before_install:
- sudo add-apt-repository ppa:fkrull/deadsnakes
- sudo apt-get update
- sudo apt-get install -y build-essential python3.5 python3-pip python3-psycopg2 python3-shapely
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
- pip install python-coveralls
script: py.test
after_success:
- coveralls
notifications:
  email: false
deploy:
  provider: pypi
  user: shongololo
  password:
    secure: fC4+/TNpsHIhviVQ18SryJ12qVeJj/FrcVOvbdhx+YZvXnYRXm6uLnSii3zsr8PYqYmVBZpiBvxsTR0X+OaGDVh0U/v58lDvcfVhJC72A5TjugcBUPjoC9e01lqJH8wKk53WgPeQY4ansED/+ydICfRFz9CqtwrgR1EujjnDgjCDi4PqdaupU1PdAfIvXDKVBAWFBfYIkxoGIUfd9d3nC8c7RpLaM/qwhKwO8KA0uxMPz0f2ZhE/sjwBoupLPchB1w7ZQ3SfKIjo2/AJ+BZTviq+K/4NhdehAvqLPlEkdPZ7Jr9jfWR6wP8HwL3/t9DAPGJI7UjNoxSBQEjUlz75F8sqQMEQB7O/iXHHhUOvsSG6D+XgAcS4FbkpgiVptKXhjf3nrnU50eMFsruDLgC4plZdl6NbEhwXi88HqeDNIU/iN0Ap6gQM3hnGB8zRTBaZ3hNe/KhnssZir4tWg1I5I7w1sRe8mM4wdDIYeGEW/lC2Ifw1asZJR2mADlS652YdbLD5taHz1TOCPMjYPqFWJSpTVt92Sz75cLtAiUEuiuRay+CbyB/hbxXzR37nnFmueyuYG9c4a7/YO+0LfL32Fq0by3Y7Oh7jzDBRNaXqK2WdelukVnQ8hSmxbWsf85+2RoHGGr3bUfZmvngUAxm0hXRU/aMbfnaoXCsg1qtlZ0s=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: shongololo/aiovectortiler
