databases:
- default: 'dbname=my_db user=my_user password= host=localhost'
default_recipe: 'example recipe'
log_level: 'info'
SRID: 3857
scale: 1
buffer: 0
clip: False
CORS: '*'

builtin_plugins: []
plugins: []

tileJSON_spec: >
  {tilejson: '2.1.0',
  name: 'aiovectortiler',
  description: 'Asynchronous micro vector tile server for PostGIS.',
  scheme: 'xyz',
  format: 'pbf',
  tiles: [
    'http://vector.myserver.org/all/{z}/{x}/{y}.pbf'
  ]}