log_level: 'info'
database:
  host: db_host
  port: db_port
  database: db_name
  user: db_user
  password: db_password
default_recipe: 'example_recipe'
SRID: 3857  # optional global parameter
scale: 1  # optional global parameter
buffer: 0  # optional global parameter
clip: False  # optional global parameter
CORS: '*'

tileJSON_spec: >
  {"tilejson": "2.1.0",
  "name": "aiovectortiler",
  "description": "Asynchronous micro vector tile server for PostGIS.",
  "scheme": "xyz",
  "format": "pbf",
  "tiles": [
    "https://vector_tile_demo_host.com/all/{z}/{x}/{y}.pbf"
  ]}
